version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: daily
      # ignore:
      # - dependency-name: "@testing-library/user-event"
      #   versions:
      #   - 13.1.3
      #   - 13.1.5
